# SigNoz Helm Chart Values
# Configuration for SigNoz as additional observability backend

global:
  storageClass: "local-path"  # K3d default storage class

# ClickHouse configuration
clickhouse:
  installCustomStorageClass: false
  persistence:
    size: 20Gi
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

# Query Service configuration
queryService:
  resources:
    requests:
      memory: "500Mi"
      cpu: "200m"
    limits:
      memory: "1Gi"
      cpu: "500m"

# OpenTelemetry Collector configuration for SigNoz
otelCollector:
  enabled: true
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "400Mi"
      cpu: "200m"

# OtelCollectorMetrics configuration
otelCollectorMetrics:
  enabled: true
  resources:
    requests:
      memory: "200Mi"
      cpu: "100m"
    limits:
      memory: "400Mi"
      cpu: "200m"

# Frontend configuration
frontend:
  service:
    type: ClusterIP
  resources:
    requests:
      memory: "100Mi"
      cpu: "50m"
    limits:
      memory: "200Mi"
      cpu: "100m"

# AlertManager configuration
alertmanager:
  enabled: true
  resources:
    requests:
      memory: "50Mi"
      cpu: "25m"
    limits:
      memory: "100Mi"
      cpu: "50m"